config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get '/', to: 'dashboard#index', as: 'admin_root', constraints: lambda { |request|
    request.env['warden'].user.present?
  }

  get '/', to: 'pages#home', as: 'root'

  resource :two_factor_auth, only: [:edit, :update],  controller: 'two_factor_auth'
  resource :email_template, only: [:edit, :update], controller: 'email_template'
  resource :user_setup, only: [:edit, :update]
  resources :secrets, only: [:show, :new, :create, :edit, :update] do
    collection { get :copy }
  end
  resources :decrypted_secrets, only: :create
  resources :extended_secrets, only: :update
  resources :subscriptions, only: [:new, :create]

  post '/decrypt_secret', to: 'decrypted_secrets#create'

  get Rails.application.config.topsekrit_google_oauth_callback_path, to: 'oauth_callbacks#google'

  get '/auth/failure', to: 'oauth_callbacks#auth_failure'

  get '/home',                 to: 'pages#home'
  get '/copyright',            to: 'pages#copyright'
  get '/privacy_policy',       to: 'pages#privacy_policy'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'

  get 'dashboard' , to: 'dashboard#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthenticatedController
  def index
    @secrets = current_user.secrets.order(created_at: :desc).first(10)

    if @secrets.empty?
      flash[:notice] = t('welcome')
      redirect_to new_secret_path
    end
  end
end

app/views/dashboard/_secret_item.erb
<% secret %>

<article id="<%= secret.id %>" class="panel secret-item">

  <header class="panel__header mail-icon<%= secret.consumed_at? ? ' light-green' : '' %>">
    <% if secret.consumed_at? %>
      <%= image_tag 'icons/unlocked-icon.svg', alt: 'Unlocked email', width: 62 %>
    <% else %>
      <%= image_tag 'icons/locked-icon.svg', alt: 'Locked Mail', width: 62  %>
    <% end %>

    <div>
      <h3 class="panel__title"><%= secret.title %></h3>
      <% if secret.consumed_at.blank? %>
        <p class="viewed-status">Not Viewed</p>
      <% else %>
        <p class="viewed-status">Viewed</p>
      <% end %>
    </div>
  </header>

  <div class="panel__body">
    <% if secret.no_email? %>
      <p>
        This secret was sent manually
        <em>(no email sent)</em>
      </p>
    <% else %>
      <p class="from"><strong>From:</strong> <%= secret.from_email %></p>
      <p class="to"><strong>To:</strong> <%= secret.to_email %></p>
    <% end %>


    <p class="sent">
      <% if secret.no_email? %>
        <strong>Created:</strong> <%= local_time(secret.created_at, t('date.formats.dashboard_time'))  %>
      <% else %>
        <strong>Sent:</strong> <%= local_time(secret.sent_at, t('date.formats.dashboard_time'))  %>
      <% end %>
    </p>

    <p class="viewed">
      <% if secret.consumed_at? %>
        <strong>Viewed:</strong> <%= local_time(secret.consumed_at, t('date.formats.dashboard_time')) %>
      <% elsif secret.expired? %>
        <strong>Not viewed:</strong> expired: <%= local_time(secret.expire_at, t('date.formats.dashboard_time')) %>
      <% else %>
        <strong>Not viewed:</strong> expiry: <%= local_time(secret.expire_at, t('date.formats.dashboard_time')) %>
      <% end %>
    </p>
    <p>
      <button class="notes-trigger button">See Notes</button>
      <span class='notes'><%= secret.comments %></span>
    <p>
  </div>

  <footer class="panel__footer">
    <% if secret.consumed_at? %>
      <div class="extend-label viewed">Viewed and Deleted</div>
    <% elsif secret.expired? && !secret.extended?%>
      <%= link_to "Extend", extended_secret_path(secret), class: 'extend-btn button blue', method: :put %>
    <% elsif secret.extended? %>
      <div class="extend-label extended">Extended</div>
    <% end %>
      <%= link_to "Send&nbsp;Another".html_safe, new_secret_path(base_id: secret.uuid), class: 'button green' %>
  </footer>
</article>

app/views/dashboard/index.html.erb
<section class="banner">
  <h1>All Secrets</h1>
  <%= link_to 'Create New', new_secret_path, class: 'button white top-buffer' %>
</section>

<div class="container dashboard">
  <div class="dashboard__secrets-list">
    <% @secrets.each do |secret| %>
      <%= render 'secret_item', secret: secret %>
    <% end %>
  </div>
</div>