config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get '/', to: 'dashboard#index', as: 'admin_root', constraints: lambda { |request|
    request.env['warden'].user.present?
  }

  get '/', to: 'pages#home', as: 'root'

  resource :two_factor_auth, only: [:edit, :update],  controller: 'two_factor_auth'
  resource :email_template, only: [:edit, :update], controller: 'email_template'
  resource :user_setup, only: [:edit, :update]
  resources :secrets, only: [:show, :new, :create, :edit, :update] do
    collection { get :copy }
  end
  resources :decrypted_secrets, only: :create
  resources :extended_secrets, only: :update
  resources :subscriptions, only: [:new, :create]

  post '/decrypt_secret', to: 'decrypted_secrets#create'

  get Rails.application.config.topsekrit_google_oauth_callback_path, to: 'oauth_callbacks#google'

  get '/auth/failure', to: 'oauth_callbacks#auth_failure'

  get '/home',                 to: 'pages#home'
  get '/copyright',            to: 'pages#copyright'
  get '/privacy_policy',       to: 'pages#privacy_policy'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'

  get 'dashboard' , to: 'dashboard#index'
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <div class="flash alert alert-<%=flash_display_type(type)=%> alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span id="flash-message"><%= message.html_safe %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid navbar navbar-static-bottom">
    <p class="attribution text-center">
      Built, hosted and maintained by <%= link_to("reinteractive", "https://reinteractive.com") %>.
    </p>
    <ul class="footer-links list-unstyled text-center">
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="">SecretLink.org</a></li>
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="/#homepage-steps">How it works</a></li>
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="/#homepage-faq">FAQ</a></li>
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="/#homepage-about">About</a></li>
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="/copyright">Copyright</a></li>
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="/privacy_policy">Privacy Policy</a></li>
      <li class="visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block"><a href="/terms_and_conditions">Terms & Conditions</a></li>
    </ul>
  </div>
</footer>

app/views/shared/_ga.html.erb
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-65184612-1', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/shared/_header.html.erb
<header class="main-nav">
  <a class="navbar-brand" href="/">
    <span class="glyphicon glyphicon-lg glyphicon-camera" aria-hidden="true"></span>
    SecretLink.org
  </a>
  <ul class="main-nav__links">
    <li><%= link_to "How it works", home_path(anchor: "homepage-steps") %></li>
    <li><%= link_to "FAQ", home_path(anchor: "homepage-faq") %></li>
    <li><%= link_to "About", home_path(anchor: "homepage-about") %></li>
    <% if user_signed_in? %>
     <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        Account <span class="caret"></span>
      </a>
      <ul class="dropdown-menu dropdown-menu-right">
        <li><%= link_to 'Dashboard', dashboard_path %></li>
        <li><%= link_to 'Settings', edit_two_factor_auth_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>
    <% else %>
      <li><%= link_to('Sign In', new_user_session_path) %></li>
    <% end %>
  </ul>
</header>

app/views/shared/_stripe_form.html.erb
<%
  charge_path
  key = local_assigns.fetch :key, Rails.configuration.topsekrit_stripe_publishable_key
%>

<%= simple_form_for(:subscription, url: charge_path,
  html: { class: "js-stripe-form", id: "payment-form", data: {key: key} }) do |form| %>

  <div class="stripe-form__row">
    <label for="card-element" class="stripe-form__label">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <div class="form__actions">
    <input type="submit" class="form__button form__button--primary" value=<%= t("buttons.purchase") %> />
  </div>

<% end %>

app/views/shared/_two_factor_fields.html.erb
<div class="two-factor-fields">
  <%= f.hidden_field(:otp_secret) %>
  <%= f.input :otp_required_for_login,
        label: 'Enable two factor authentication',
        input_html: { class: 'otp-required-for-login' }
  %>

  <div class="enable-otp-fields">
    <div class="form-group otp-step">
      <img
        class="qrcode"
        src="data:image/png;base64,<%= Base64.encode64(RQRCode.render_qrcode(otp_provisioning_uri, :png, {})).html_safe %>"
      />
    </div>

    <%= f.input :otp_attempt,
          label: '6 digit code',
          value: '',
          autocomplete: 'off'
        %>
  </div>
</div>

app/views/shared/_two_factor_links.html.erb
<%= link_to 'Two Factor Auth (2FA)', edit_two_factor_auth_path %>
<%= link_to 'Email Template', edit_email_template_path %>