config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get '/', to: 'dashboard#index', as: 'admin_root', constraints: lambda { |request|
    request.env['warden'].user.present?
  }

  get '/', to: 'pages#home', as: 'root'

  resource :two_factor_auth, only: [:edit, :update],  controller: 'two_factor_auth'
  resource :email_template, only: [:edit, :update], controller: 'email_template'
  resource :user_setup, only: [:edit, :update]
  resources :secrets, only: [:show, :new, :create, :edit, :update] do
    collection { get :copy }
  end
  resources :decrypted_secrets, only: :create
  resources :extended_secrets, only: :update
  resources :subscriptions, only: [:new, :create]

  post '/decrypt_secret', to: 'decrypted_secrets#create'

  get Rails.application.config.topsekrit_google_oauth_callback_path, to: 'oauth_callbacks#google'

  get '/auth/failure', to: 'oauth_callbacks#auth_failure'

  get '/home',                 to: 'pages#home'
  get '/copyright',            to: 'pages#copyright'
  get '/privacy_policy',       to: 'pages#privacy_policy'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'

  get 'dashboard' , to: 'dashboard#index'
end

app/controllers/two_factor_auth_controller.rb
class TwoFactorAuthController < AuthenticatedController
  def edit
    @tfa_service = TwoFactorService.new(current_user)
    @tfa_service.issue_otp_secret
    @otp_provisioning_uri = @tfa_service.generate_otp_provisioning_uri
  end

  def update
    @tfa_service = TwoFactorService.new(current_user)

    valid =
      if enabling_otp?
        @tfa_service.enable_otp(
          two_factor_params[:otp_secret],
          two_factor_params[:otp_attempt],
          two_factor_params[:current_password]
        )
      else
        @tfa_service.disable_otp(two_factor_params[:current_password])
      end

    if valid
      verb = @tfa_service.user.otp_required_for_login ? 'enabled' : 'disabled'
      redirect_to root_path, notice: t('two_factor.update_success', verb: verb)
    else
      flash[:error] = t('two_factor.update_failed')

      @otp_provisioning_uri = @tfa_service.generate_otp_provisioning_uri
      render :edit
    end
  end

  private

  def enabling_otp?
    two_factor_params[:otp_required_for_login] == '1'
  end

  def two_factor_params
    params.require(:user).permit(:otp_required_for_login, :otp_secret, :otp_attempt, :current_password)
  end
end

app/views/two_factor_auth/edit.html.erb
<section class="banner">
  <h1>Account Settings</h1>
</section>

<section class="devise_page two-column">
  <article class="panel">
    <header class="panel__header">
      <h2 class="panel__title">Two Factor Auth (2FA)</h2>
    </header>
    <div class="panel__body">
    <%= simple_form_for(@tfa_service.user, url: two_factor_auth_path, html: {class: "devise_page__form"}) do |f| %>
      <%= render partial: 'shared/two_factor_fields', locals: {
        f: f,
        resource: @tfa_service.user,
        otp_provisioning_uri: @otp_provisioning_uri
      } %>

      <%= f.input :current_password,
              label: "Current password".html_safe,
              input_html: { autocomplete: "off" } %>

      <div class="form-actions">
        <%= f.button :submit, name: :two_factor, value: 'Save Settings', class: 'btn-enable-2fa button green' %>
      </div>
    <% end %>
    </div>
  </article>

  <aside class="secret__instructions">
    <ol>
      <li class="one">
        <% if @tfa_service.user.otp_required_for_login %>
          <%# User is already enrolled for 2fa. %>
          Use the form to connect a new device (this will disconnect your previous device).
        <% else %>
          <%# User is not enrolled for 2fa; show them how to get set up %>
          Install a two-factor app, such as Google Authenticator, on your smartphone.
          <div>
            <a target="_blank" href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8">
              <%= image_tag "apple-app-store.png", class: "app-store-icon store-icon", alt: "Download on the App store", width: 160 %>
            </a>
            <a target="_blank" href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2">
              <%= image_tag "google-play-store.png", class: "app-store-icon store-icon", alt: "Get it on Google Play", width: 160 %>
            </a>
          </div>
        <% end %>
      </li>
      <li class="two">Open your two-factor app and scan the barcode.</li>
      <li class="three">Enter the 6 digit code from two-factor app.</li>
    </ol>
  </aside>

  <div class="devise_page__links">
    <%= render "shared/two_factor_links" %>
  </div>
</section>