config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get '/', to: 'dashboard#index', as: 'admin_root', constraints: lambda { |request|
    request.env['warden'].user.present?
  }

  get '/', to: 'pages#home', as: 'root'

  resource :two_factor_auth, only: [:edit, :update],  controller: 'two_factor_auth'
  resource :email_template, only: [:edit, :update], controller: 'email_template'
  resource :user_setup, only: [:edit, :update]
  resources :secrets, only: [:show, :new, :create, :edit, :update] do
    collection { get :copy }
  end
  resources :decrypted_secrets, only: :create
  resources :extended_secrets, only: :update
  resources :subscriptions, only: [:new, :create]

  post '/decrypt_secret', to: 'decrypted_secrets#create'

  get Rails.application.config.topsekrit_google_oauth_callback_path, to: 'oauth_callbacks#google'

  get '/auth/failure', to: 'oauth_callbacks#auth_failure'

  get '/home',                 to: 'pages#home'
  get '/copyright',            to: 'pages#copyright'
  get '/privacy_policy',       to: 'pages#privacy_policy'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'

  get 'dashboard' , to: 'dashboard#index'
end

app/models/secret.rb
class Secret < ApplicationRecord
  attr_accessor :secret_key

  attr_encrypted :secret, key: :secret_key, mode: :per_attribute_iv_and_salt
  #attr_encrypted_encrypted_attributes #:secret, key: :secret_key, mode: :per_attribute_iv_and_salt
  mount_uploader :secret_file, SecretFileUploader

  validates :from_email, presence: {
                           message: "Please enter the senders's email address"
                         }

  validates :to_email, presence: {
                         message: "Please enter the senders's email address"
                       }

  validates :secret, presence: {
                        message: "Please enter a secret to share with the recipient",
                     }

  validate :expire_at_within_limit
  validate :email_domain_authorised

  scope :with_email_and_access_key, ->(email, access_key){
    where('from_email = ? and access_key = ?', email, access_key)
  }

  def delete_encrypted_information
    update_attribute(:secret, nil)
  end

  def mark_as_consumed
    update_attribute(:consumed_at, Time.now)
  end

  def expired?
    expire_at.present? && expire_at < Time.now
  end

  def expire_at_within_limit
    if Rails.application.config.topsekrit_maximum_expiry_time
      max_expiry_in_config = (Time.now + Rails.application.config.topsekrit_maximum_expiry_time).to_i
      if expire_at.blank? || (expire_at && expire_at.to_i > max_expiry_in_config)
        errors.add(:expire_at, "Maximum expiry allowed is " +
        (Time.now + Rails.application.config.topsekrit_maximum_expiry_time).strftime('%d %B %Y'))
      end
    end
  end

  def email_domain_authorised
    if closed? && email_domain_does_not_match?
      errors.add(:base, "This system has been locked to only allow secrets to be sent to #{authorised_domain} email addresses.")
    end
  end

  def authorised_domain
    Rails.configuration.topsekrit_authorised_domain
  end

  def closed?
    [:closed].include?(Rails.configuration.topsekrit_authorisation_setting)
  end

  def email_domain_does_not_match?
    AuthorisedEmailService.email_domain_does_not_match?(to_email)
  end

  def self.expire_at_hint
    if Rails.application.config.topsekrit_maximum_expiry_time
      (Date.today + 1).strftime('%d %B %Y') + ' - ' +
      (Time.now + Rails.application.config.topsekrit_maximum_expiry_time).strftime('%d %B %Y')
    end
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  include RetrieveSecret
  before_action :retrieve_secret, only: :show
  before_action :require_validated_email, only: [:new, :create]

  def show
    # As the receipient has now clicked a link, we know their email address is also
    # valid, so we will validate them so they can painlessly send a new secret if
    # they like as well.
    validate_email!(@secret.to_email)
  end

  def new
    @secret = Secret.new(from_email: validated_email)
  end

  def create
    @secret = SecretService.encrypt_new_secret(secret_params)
    if @secret.persisted?
      flash[:message] = "The secret has been encrypted and an email sent to the recipient, feel free to send another secret!"
      redirect_to new_secret_path
    else
      flash.now[:message] = @secret.errors.full_messages.join("<br/>".html_safe)
      render :new
    end
  end

  private

  def secret_params
    params.require(:secret).permit(:title, :to_email, :secret, :comments,
                                   :expire_at, :secret_file).tap do |p|
      p[:from_email] = validated_email
    end
  end

end

app/views/secrets/_secret.html.erb
<tr id="secret-<%= secret.id %>">
  <td><%= secret.to_email %></td>
  <td><%= secret.title %></td>
  <td><%= secret.status %></td>
  <td><%= secret.expire_at.try(:strftime, '%d %B %Y') %></td>
  <td><%= secret.created_at.try(:strftime,'%d %B %Y') %></td>
</tr>

app/views/secrets/copy.html.erb
<div class="container copy-link">
  <div class="row">
    <h2 class="main-header">Copy Link</h2>
  </div>
  <div class="row">
    <pre><%= secret_url(@data[:uuid], key: @data[:key]) %></pre>
    <div class="message">
      Make sure you copied the link before hitting the close button. You cannot go back to this page.
    </div>
  </div>
</div>

app/views/secrets/new.html.erb
<section class="banner">
  <h1>Create a new secret to send</h1>
</section>

<section class="application-container secret">
  <div class="secret__flex-container">
    <%= simple_form_for @secret, url: secrets_url, wrapper: 'horizontal_form', html: {class: 'form-horizontal secret__form js-new-secret-form'} do |f| %>
      <div class='form-group'>
        <%= f.input :title, input_html: { class: 'form-control' } %>
        <div class='col-sm-9 col-sm-offset-3'>
          <%= f.input :no_email, label: "Copy the link (don't send email)", input_html: { class: 'no-email-toggle' } %>
        </div>
        <%= f.input :from_email, label: "Sender:", input_html: { disabled: true, placeholder: from_email_placeholder, class: 'form-control' } %>
        <%= f.input :to_email, label: "Recipient:", input_html: { placeholder: to_email_placeholder, class: 'form-control' } %>
        <%= f.input :secret, as: :text, input_html: { class: 'form-control' } %>
      </div>
      <div class='form-group'>
        <%= f.input :expire_at, as: :string, input_html: { value: 5.days.from_now.to_date.strftime('%d %B, %Y'), class: 'datepicker form-control' } %>
        <%= f.input :comments, input_html: { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
         <%= f.button :submit, 'Send your Secret', class: 'button green' %>
        </div>
      </div>
    <% end %>
    <aside class="secret__instructions">
      <ol>
        <li class="one">Enter the recipients email address, and enter or attach the secret information.</li>
        <li class="two">A link with a one-time authentication token is sent to the recipient's address.</li>
        <li class="three">When the recipient views the information, it is deleted from the database.</li>
      </ol>
    </aside>
  </div>
</section>

app/views/secrets/show.html.erb
<section class="banner">
  <h1>Hello <%= @secret.to_email %></h1>
</section>

<div class="application-container secret">
  <div class='row'>
    <div class="col-md-6 col-md-offset-3">

      <p>
        <b><%= @secret.from_email %></b> has shared a secret with you.
      </p>
      <p>
        It will be <b>deleted</b> from our system once you view it, so be sure to make a copy.
      </p>

      <% if @secret.title.present? %>
        <p>
          <strong>Title:</strong>
          <%= @secret.title %>
        </p>
      <% end %>

      <% if @secret.comments.present? %>
        <p>
          <strong>Comments:</strong>
        </p>
        <pre><%= @secret.comments %></pre>
      <% end %>

      <p>
        <strong>Secret:</strong>
      </p>
      <p>
        <% if @unencrypted_secret || flash.now[:error] %>
        <pre><%= @unencrypted_secret %></pre>
        <% elsif @secret.encrypted_secret.blank? %>
        <pre>Secret has already been displayed and deleted.</pre>
        <% else %>
          <%= form_tag '/decrypt_secret' do |f| %>
            <%= hidden_field_tag 'id', @secret.uuid %>
            <%= hidden_field_tag 'key', params[:key] %>
            <%= submit_tag 'Click here to show the secret', class: 'btn btn-primary btn-lg' %>
          <% end %>
        <% end %>
      </p>
      <br />
      <% unless current_user.present? %>
        <div>
          <span>Start sending your secret.</span>
          <%= link_to 'Register Here', new_user_registration_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>